#ifndef __CONFIG_GARY_H__
#define __CONFIG_GARY_H__

#define DISP_BW_V2DISP_3C_B
#define UNITS_TEMP_CELSIUS
#define UNITS_SPEED_KILOMETERSPERHOUR
#define UNITS_PRES_MILLIMETERSOFMERCURY
#define UNITS_DIST_KILOMETERS
#define UNITS_HOURLY_PRECIP_POP
#define UNITS_DAILY_PRECIP_MILLIMETERS

#define OUTLOOK_VERTICAL_LINE_INTERVAL 24

#endif
