#ifndef __CONFIG_GARY_H__
#define __CONFIG_GARY_H__

#define DISP_BW_V2
#define UNITS_TEMP_FAHRENHEIT
#define UNITS_SPEED_MILESPERHOUR
#define UNITS_PRES_INCHESOFMERCURY
#define UNITS_DIST_MILES
#define UNITS_HOURLY_PRECIP_POP
#define UNITS_DAILY_PRECIP_INCHES

#define OUTLOOK_VERTICAL_LINE_INTERVAL 24

#endif
